blueprints/auth.py
from flask import Blueprint,render_template,url_for,redirect,flash
from flask_login import login_required,login_user,logout_user,current_user
from forms import RegisterForm,LoginForm
from model import User
from extensions import db
from settings import Operations
from mail import send_confirm_email,send_reset_password_email
from utils import generate_token,validate_token
auth_bp=Blueprint('auth',__name__)

@auth_bp.route('/login',methods=['GET','POST'])
def login():
    form=LoginForm()
    if form.validate_on_submit():
        username=form.username.data
        password=form.password.data
        remember=form.remember.data
        user=User.query.filter_by(username=username).first()
        if user and user.validate_password(password):
            print('登录成功')
            flash('登录成功！','success')
            login_user(user=user,remember=remember)
            print(current_user)
            if current_user.confirmed:
                return redirect(url_for('main.index'))
            else:
                return render_template('confirm.html')
        else:
            flash('账号不存在或者密码错误！')
    return render_template('login.html',form=form)


@auth_bp.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        user = User(username=username, email=email)

        user.set_password(password)
        user.generate_email_hash()
        db.session.add(user)
        db.session.commit()
        token = generate_token(user=user, operation=Operations.CONFIRM)
        send_confirm_email(user=user, token=token)
        flash('邮件发送成功，请尽快确认！', 'success')
        return redirect(url_for('.login'))
    return render_template('register.html',form=form)

@auth_bp.route('/forget-password',methods=['GET','POST'])
def forget_password():
    pass

@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    print('token')
    if current_user.confirmed:
        print(current_user.username)
        return redirect(url_for('main.index'))
    if validate_token(user=current_user,token=token,operation=Operations.CONFIRM):
        print('验证成功')
        flash('验证成功','success')
        return redirect(url_for('main.index'))
    else:
        print('验证失败')
        flash('验证失败','danger')
        return redirect(url_for('.resend_confirmation'))

@auth_bp.route('/profile/<username>')
@login_required
def profile(username):
    user=User.query.filter_by(username=username).first()
    return render_template('profile.html',user=user)

@auth_bp.route('/logout')
@login_required
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('main.index'))

blueprints/main.py
from flask import Blueprint,render_template,url_for,redirect,request,flash
from extensions import db
from model import Recipe
import requests
import re
from lxml import etree
from utils import redirect_back
import time
from sqlalchemy.sql.expression import func
main_bp=Blueprint('main',__name__)

@main_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Recipe.query.filter_by(t='new').order_by(func.random()).paginate(page, per_page=20)
    recipes = pagination.items
    count=Recipe.query.count()
    return render_template('index.html',pagination=pagination,recipes=recipes,count=count)

@main_bp.route('/new-recipe')
def new_recipe():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='new').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/new.html',pagination=pagination,recipes=recipes)


@main_bp.route('/hot')
def hot():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='hot').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/hot.html',pagination=pagination,recipes=recipes)
@main_bp.route('/cold')
def cold():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='cold').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/cold.html',pagination=pagination,recipes=recipes)
@main_bp.route('/main')
def main():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='main').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/main.html',pagination=pagination,recipes=recipes)
@main_bp.route('/soup')
def soup():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='soup').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/soup.html',pagination=pagination,recipes=recipes)
@main_bp.route('/snack')
def snack():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='snake').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/snack.html',pagination=pagination,recipes=recipes)

@main_bp.route('/west')
def west():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='west').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/west.html',pagination=pagination,recipes=recipes)
@main_bp.route('/bake')
def bake():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='bake').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/bake.html',pagination=pagination,recipes=recipes)
@main_bp.route('/selfmade')
def selfmade():
    page=request.args.get('page',1,type=int)
    pagination=Recipe.query.filter_by(t='selfmade').order_by(func.random()).paginate(page,per_page=20)
    recipes=pagination.items
    return render_template('t/selfmade.html',pagination=pagination,recipes=recipes)


@main_bp.route('/detail/<uid>')
def detail(uid):
     headers={
          'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36',
          'authority':'home.meishichina.com',
     }
     recipe=Recipe.query.filter_by(uid=uid).first()
     url='https://home.meishichina.com/recipe-'+str(uid)+'.html'
     data=requests.get(url,headers=headers).content.decode('utf-8')
     step=re.compile('<div class="recipeStep">([\s\S]*?)</div>\n<div class="mo">').findall(data)
     ingredient = recipe.ingredient.split('、')
     message = re.compile('<span class="txt_tart">“</span>(.*?)<span class="txt_end">”').findall(data)
     imageurl = re.compile('<span></span><img src="(.*?)" alt').findall(data)
     print(message)
     if (len(message)) == 0:
         message = '无介绍'
     else:
         message = message[0]
     if len(step)!=0:
          step='<div class="recipeStep">'+step[0]+'</div>'
          return render_template('detail.html',step=step,ingredient=ingredient,recipe=recipe,message=message,imageurl=imageurl[0])
     else:
          print('第一次获取数据失败！')
          print(recipe.uid)
          step = re.compile('<div class="recipeStep">([\s\S]*?)</div>\n<div class="recipeTip mt16').findall(data)
          step = '<div class="recipeStep">' + step[0] + '</div>'
          if len(step)==0:
             flash('数据获取失败！','info')
             return redirect_back()
          else:
              return render_template('detail.html', step=step, ingredient=ingredient, recipe=recipe, message=message,imageurl=imageurl[0])
     #print(data.text)
     #step=re.compile('<div class="recipeStep">(.*?)</div>').findall(data.text)
     #a=etree.html(data.text)

     #return render_template('detail.html')



@main_bp.route('/search')
def search():
     q=request.args.get('q')
     if q=='':
          flash('请重新输入！','info')
          return redirect_back()

     page = request.args.get('page', 1, type=int)
     pagination=Recipe.query.whooshee_search(q).paginate(page,per_page=20)
     results=pagination.items
     return render_template('search.html',pagination=pagination,results=results,q=q)

templates/base.html
{% from 'macros.html' import nav_link %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-KK菜谱大全</title>
     {% block head %}
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
        <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

    <link rel="icon" href="{{ url_for('static',filename='favicon.ico') }}">
    {% endblock %}
</head>
<body>

{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container">


    <a class="navbar-brand" href="/">KK菜谱大全</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            {{ nav_link('main.index','首页') }}
            {{ nav_link('main.index','菜谱') }}
            {{ nav_link('main.index','食材') }}
            {{ nav_link('main.index','关于') }}
                    <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}">
            <input class="form-control mr-sm-2" type="search" placeholder="搜索菜谱、食材..." aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>
        </ul>
         <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item" {% if request.endpoint and request.endpoint==endpoint %}active{% endif %}>
                 <a class="nav-link" href="{{ url_for('auth.profile',username=current_user.username) }}">{{ current_user.username }}</a>

                 </li>
            {{ nav_link('auth.logout','注销') }}
        {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">登录</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{{ url_for('auth.register') }}">注册</a>
        {% endif %}
         </div>






    </div>
</div>
</nav>

{% endblock %}


<main class="container">
    <br>
    {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
    {% endfor %}
    {% block content %} {% endblock %}

</main>



{% block scripts %}
{{ moment.include_moment(local_js=url_for('static',filename='js/moment-with-locales.min.js')) }}
{{ moment.locale(auto_detect=True) }}
 <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
{% endblock %}


{% block footer %}
<center>
<footer >
            <small> &copy; 2018 <a href="http://www.baidu.com" title="Written by KK">KK</a> /
            <a href="https://github.com/PythonerKK" title="Fork me on GitHub">GitHub</a> /
            all right reserved.
        </small>
</footer>
    </center>
    {% endblock %}
</body>
</html>

templates/base_index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block content %}

{% block card %}
       <ul class="nav nav-pills">
        <li class="nav-item">
            <a href="#" class="nav-link disabled">菜谱分类 </a>
        </li>
        <li class="nav-item">
            <a href="{{ url_for('main.new_recipe') }}" class="nav-link active">最新推荐</a>
        </li>
        <li class="nav-item">
            <a href="{{ url_for('main.hot') }}" class="nav-link">热菜</a>
        </li>
    <li class="nav-item">
            <a href="{{ url_for('main.cold') }}" class="nav-link">凉菜</a>
        </li>
        <li class="nav-item">
            <a href="{{ url_for('main.main') }}" class="nav-link">主食</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.soup') }}" class="nav-link">汤羹</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.snack') }}" class="nav-link">小吃</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.west') }}" class="nav-link">西餐</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.bake') }}" class="nav-link">烘焙</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.selfmade') }}" class="nav-link">自制</a>
        </li>


    </ul>
{% endblock %}


{% endblock %}

templates/confirm.html
{% extends 'base.html' %}

{% block content %}

    <br><br>
    <h1 align="center">请登录邮箱确认您的账号</h1>
    <center><a href="{{ url_for('main.index') }}">点击这里返回首页</a></center>


{% endblock %}

{% block footer%}{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-md-8">
            <h1>{{ recipe.name }}的做法</h1>
            <br>
            <div class="card">
              <img class="card-img-top" src="{{ imageurl }}"  alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title">{{ recipe.name }}</h5>
                <p class="card-text">{{ message }}</p>
                <a href="#" class="btn btn-primary">收藏</a>
              </div>
            </div>
            <br>

            <h3 style="color: deepskyblue">所需食材</h3>

                <p>{{ recipe.ingredient }}</p>

            <br>

            <h3 style="color: deepskyblue">做法步骤</h3>

            {{ step|safe }}

        </div>

        <div class="col-md-4">
        <div class="list-group">

            <h1>材料列表</h1>
            {% for i in ingredient %}
                <a href="{{ url_for('main.search',q=i) }}"><button type="button" class="list-group-item list-group-item-action">{{ i }}</button></a>
            {% endfor %}
    </div>
        </div>

    </div>




{% endblock %}

templates/index.html
{% extends 'base_index.html' %}

{% block content %}
    <div class="page-header"><h1>KK菜谱大全 <small>(共有{{ count }}个菜谱被收录)</small></h1><h5 style="color: deepskyblue;">吃货的天堂，实时更新</h5></div>

{#    <section class="banner">#}
{#  <div class="homepage-banner">#}
{#    <h1 class="homepage-banner__title">Find, install and publish Python packages with the Python Package Index</h1>#}
{##}
{#    <form class="search-form search-form--large search-form--fullwidth" action="/search/">#}
{#      <label for="search" class="sr-only">Search PyPI</label>#}
{#      <input id="search" class="search-form__search large-input" type="text" name="q" placeholder="Search projects">#}
{#      <button type="submit" class="search-form__button">#}
{#        <i class="fa fa-search" aria-hidden="true"></i>#}
{#        <span class="sr-only">Search</span>#}
{#      </button>#}
{#    </form>#}
{##}
{#    <p class="homepage-banner__browse">Or <a href="/search/">browse projects</a></p>#}
{#  </div>#}
{#</section>#}



    <br>

{% block card %}
       <ul class="nav nav-pills">
        <li class="nav-item">
            <a href="#" class="nav-link disabled">菜谱分类 </a>
        </li>
        <li class="nav-item">
            <a href="{{ url_for('main.new_recipe') }}" class="nav-link active">最新推荐</a>
        </li>
        <li class="nav-item">
            <a href="{{ url_for('main.hot') }}" class="nav-link">热菜</a>
        </li>
    <li class="nav-item">
            <a href="{{ url_for('main.cold') }}" class="nav-link">凉菜</a>
        </li>
        <li class="nav-item">
            <a href="{{ url_for('main.main') }}" class="nav-link">主食</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.soup') }}" class="nav-link">汤羹</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.snack') }}" class="nav-link">小吃</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.west') }}" class="nav-link">西餐</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.bake') }}" class="nav-link">烘焙</a>
        </li>
              <li class="nav-item">
            <a href="{{ url_for('main.selfmade') }}" class="nav-link">自制</a>
        </li>


    </ul>
{% endblock %}

        <br>
    <div class="row">
        {% if recipes %}
            {% for recipe in recipes %}

                    <div class="photo-card card col-sm-3" style="width: 20rem;">
                        <a href="{{ url_for('main.detail',uid=recipe.uid) }}" class="card-thumbnail" target="blank">
                            <img src="{{ recipe.imageurl }}" class="card-img-top" >

                        </a>
                        <div class="card-body">

                            <p>{{ recipe.name }}</p>
                        </div>
                    </div>
            {% endfor %}
        {% endif %}

    </div>

        <div class="pagination" align="center">
{% from 'macros.html' import pager %}
    {{ pager(pagination) }}
        </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% from 'macros.html' import form_field %}

<br>

{% block content %}
    <div class="page-header"><h1>登录账号</h1></div>
    <form action="{{ url_for('auth.login') }}" method="post">
        <div class="form-control" align="center">
            {{ form.csrf_token }}
        <div class="form-group">
            {{ form_field(form.username) }}
        </div>
                <div class="form-group">
            {{ form_field(form.password) }}
        </div>
                <div class="form-group">
            {{ form_field(form.remember) }}
        </div>
        <p class="small"><a href="{{ url_for('auth.register') }}">注册新账号</a></p>
        <p class="small"><a href="{{ url_for('auth.forget_password') }}">忘记密码</a></p>

        <div class="form-group">
            {{ form.submit(class='btn btn-primary') }}
        </div>

        </div>
    </form>

{% endblock %}

{% block footer %}{% endblock %}

templates/macros.html
{% macro form_field(field) %}
    {{ field.label }}<br>
    {{ field(**kwargs) }}<br>
    {% if field.errors %}
        {% for error in field.errors %}
            <small class="error">{{ error }}</small>
        {% endfor %}
    {% endif %}
{% endmacro %}

{% macro nav_link(endpoint,text) -%}
    <li class="nav-item" {% if request.endpoint and request.endpoint==endpoint %}active{% endif %}>
        <a class="nav-link" href="{{ url_for(endpoint,**kwargs) }}">{{ text }}</a>

    </li>

{%- endmacro %}

{% macro pager(pagination,fragment='') %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item" {% if not pagination.has_prev %}disabled{% endif %}>
            <a href="{{ url_for(request.endpoint,page=pagination.prev_num,**kwargs)+'&q='+fragment if pagination.has_prev else '#' }}" class="page-link">
                前一页
            </a>
        </li>
        <li class="page-item" {% if not pagination.has_next %}disabled{% endif %}>
            <a class="page-link" href="{{ url_for(request.endpoint,page=pagination.next_num,**kwargs)+'&q='+fragment if pagination.has_next else '#' }}">
                下一页
            </a>
        </li>
    </ul>
</nav>
{% endmacro %}



{% macro photo_card(photo) %}

<div class="photo-card card col-sm-3" style="width: 20rem;">
    <a href="#" class="card-thumbnail" target="blank">
        <img src="{{ photo.imageurl }}" class="card-img-top" >

    </a>
    <div class="card-body">
        <p>{{ photo.name }}</p>
    </div>
</div>
{% endmacro %}

templates/mail_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>确认账号</title>
</head>
<body>
<h1>点击以下链接来完成注册</h1>
<a href="{{ url_for('auth.confirm',token=token,_external=True) }}">{{ url_for('auth.confirm',token=token,_external=True) }}</a>

</body>
</html>

templates/profile.html
{% extends 'base.html' %}

{% block title %}个人中心{% endblock %}

{% block content %}
    <div class="page-header"><h1>个人信息</h1></div>
    <div class="row">
        <div class="col-md-4">

            <div class="card" style="width: 18rem;">
                  <div class="card-body">
                      <img src="{{ user.gravatar }}" class="img-fluid rounded avatar-1">
                    <h5 class="card-title">{{ user.username }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted"></h6>
                    <p class="card-text">{{ user.email }}</p>
                    <a href="#" class="card-link">更换邮箱</a>
                    <a href="#" class="card-link">删除账号</a>
                  </div>
                </div>
        </div>

        <div class="col-md-8">

        </div>

    </div>

{% endblock %}

{% block footer %}

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% from 'macros.html' import form_field %}

<br>

{% block content %}
    <div class="page-header"><h1>注册账号</h1></div>
    <form action="{{ url_for('auth.register') }}" method="post">
        <div class="form-control" align="center">
            {{ form.csrf_token }}
        <div class="form-group">
            {{ form_field(form.username) }}
        </div>
                <div class="form-group">
            {{ form_field(form.email) }}
        </div>
                <div class="form-group">
            {{ form_field(form.password) }}
        </div>
            <div class="form-group">
            {{ form_field(form.password2) }}
        </div>

        <div class="form-group">
            {{ form.submit(class='btn btn-primary') }}
        </div>

        </div>
    </form>

{% endblock %}

{% block footer %}{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% from 'macros.html' import photo_card with context %}
{% block title %}{{ q }}{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>{{ q }}的搜索结果({{ results|length }})：</h1>
    </div>


        <div class="row">
        {% if results %}
            {% for result in results %}

                    <div class="photo-card card col-sm-3" style="width: 20rem;">
                        <a href="{{ url_for('main.detail',uid=result.uid) }}" class="card-thumbnail" target="blank">
                            <img src="{{ result.imageurl }}" class="card-img-top" >

                        </a>
                        <div class="card-body">

                            <a href="{{ url_for('main.detail',uid=result.uid) }}"><h5>{{ result.name }}</h5></a>
                            <p>材料：{{ result.ingredient }}</p>
                        </div>
                    </div>
            {% endfor %}
        {% endif %}

    </div>
    {% if results %}
        <div class="pagination" align="center">
{% from 'macros.html' import pager %}
    {{ pager(pagination,fragment=q) }}
        </div>
    {% endif %}


{% endblock %}

{% block footer %}{% endblock %}